- name: Gather package facts
  ansible.builtin.package_facts:
    manager: apt

- name: Fail if Nginx is not installed
  ansible.builtin.fail:
    msg: "Nginx is not installed on {{ inventory_hostname }}"
  when: "'nginx' not in ansible_facts.packages"
