- name: Create nginx instance catalogs
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ nginx_static_dir }}/{{ nginx_vhost.server_name }}", owner: "www-data", group: "www-data", mode: "0755" }
    - { path: "{{ nginx_ssl_live_dir }}/{{ nginx_vhost.server_name }}", owner: "root", group: "root", mode: "0755" }
    - { path: "{{ nginx_ssl_custom_dir }}/{{ nginx_vhost.server_name }}", owner: "root", group: "root", mode: "0755" }
