- name: Ensure email variable is defined
  fail:
    msg: "Required variable 'nginx_certbot_email' (pass via -e nginx_certbot_email=<name>)"
  when: nginx_certbot_email is undefined

- name: Check if certificate already exists
  ansible.builtin.stat:
    path: "{{ nginx_ssl_certificate }}"
  register: nginx_cert_stat

- name: Fail if certbot is not installed
  ansible.builtin.fail:
    msg: "certbot is not installed on {{ inventory_hostname }}"
  when: "'certbot' not in ansible_facts.packages"

- name: Fail if acme instance is off
  ansible.builtin.uri:
    url: "http://localhost/acme"
    return_content: true
  register: acme_health
  failed_when: acme_health.status != 200 or acme_health.content != 'OK'
  when: not nginx_cert_stat.stat.exists

- name: Get Let's Encrypt certificate
  ansible.builtin.command:
    cmd: >-
      certbot certonly --webroot
      --config-dir {{ nginx_ssl }}
      -w "{{ nginx_acme_root }}"
      -d "{{ nginx_server_name }}"
      -m "{{ nginx_certbot_email }}"
      --non-interactive
      --agree-tos
  when: not nginx_cert_stat.stat.exists

- name: Add certbot renewal cron
  ansible.builtin.cron:
    name: "certbot renew {{ nginx_instance }}"
    cron_file: "certbot-{{ nginx_instance | regex_replace('\\.', '-') }}"
    user: root
    special_time: daily
    job: 'certbot renew --config-dir {{ nginx_ssl }} --quiet --deploy-hook "systemctl reload nginx.{{ nginx_instance }}"'
  when: not nginx_cert_stat.stat.exists
