- name: Ensure instance variable is defined
  fail:
    msg: "Required variable 'nginx_instance' (pass via -e nginx_instance=<name>)"
  when: nginx_instance is undefined

- name: Load instance variables
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/{{ nginx_instance }}.yml"

- name: Check prerequisites
  ansible.builtin.import_tasks: 01_check_prerequisites.yml
  when: nginx_check_prerequisites | bool

- name: Create catalogs
  ansible.builtin.import_tasks: 02_create_catalogs.yml
  when: nginx_create_catalogs | bool

- name: Issue certificates
  ansible.builtin.import_tasks: 03_issue_certificates.yml
  when: nginx_issue_certificates | bool

- name: Generate dhparams
  ansible.builtin.import_tasks: 04_generate_dhparams.yml
  when: nginx_generate_dhparams | bool

- name: Template configs
  ansible.builtin.import_tasks: 05_template_configs.yml
  when: nginx_template_configs | bool

- name: Template static
  ansible.builtin.import_tasks: 06_template_static.yml
  when: nginx_template_static | bool

- name: Deploy service
  ansible.builtin.import_tasks: 07_template_service.yml
  when: nginx_template_service | bool
