- name: Ensure instance variable is defined
  ansible.builtin.fail:
    msg: "Required variable 'nginx_instance' (pass via -e nginx_instance=<name>)"
  when: nginx_instance is not defined

- name: Load instance variables
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/{{ nginx_instance }}.yml"

- name: Check prerequisites
  ansible.builtin.import_tasks: 01_check_prerequisites.yml
  when: nginx_check_prerequisites | bool

- name: Create instance directories
  ansible.builtin.include_tasks: 02_create_instance_directories.yml

- name: Create instance directories
  ansible.builtin.include_tasks: 02_create_instance_symlinks.yml

- name: Create vhost directories
  ansible.builtin.include_tasks: 03_create_vhost_directories.yml
  loop: "{{ nginx_vhosts }}"
  loop_control:
    loop_var: nginx_vhost

- name: Issue Let's Encrypt certificates
  ansible.builtin.include_tasks: 04_issue_letsencrypt_certificates.yml
  loop: "{{ nginx_vhosts }}"
  loop_control:
    loop_var: nginx_vhost
  when: nginx_vhost.ssl.type == 'letsencrypt'

- name: Deploy custom certificates
  ansible.builtin.include_tasks: 05_deploy_custom_certificates.yml
  loop: "{{ nginx_vhosts }}"
  loop_control:
    loop_var: nginx_vhost
  when: nginx_vhost.ssl.type == 'custom'

- name: Generate DH parameters
  ansible.builtin.import_tasks: 06_generate_dhparams.yml
  when: nginx_generate_dhparams | bool

- name: Deploy vhost static content
  ansible.builtin.include_tasks: 07_copy_static.yml
  loop: "{{ nginx_vhosts }}"
  loop_control:
    loop_var: nginx_vhost

- name: Generate nginx configuration
  ansible.builtin.import_tasks: 08_template_configs.yml
  when: nginx_generate_configs | bool

- name: Configure instance systemd service
  ansible.builtin.import_tasks: 09_template_service.yml
  when: nginx_template_service | bool
