nginx_check_prerequisites: true
nginx_create_catalogs: true
nginx_issue_certificates: true
nginx_template_configs: true
nginx_template_service: true

nginx_instance: "default"

nginx_static_root: "{{ services_apps_root }}/nginx/{{ nginx_instance }}/static"
nginx_conf_root: "{{ services_apps_root }}/nginx/{{ nginx_instance }}/conf"
nginx_var_root: "{{ services_apps_root }}/nginx/{{ nginx_instance }}/var"
nginx_log_root: "{{ services_logs_root }}/nginx/{{ nginx_instance }}"
# Configs to include into nginx.conf
nginx_conf_d: "{{ nginx_conf_root }}/conf.d"
# Reusable params configs
nginx_common: "{{ nginx_conf_root }}/common"
# Server certificates, keys  etc.
nginx_ssl: "{{ nginx_conf_root }}/ssl"

ngxin_ssl_certificate: "{{ nginx_ssl }}/cert.pem"
nginx_ssl_certificate_key: "{{ nginx_ssl }}/key.pem"
nginx_ssl_dhparams: "{{ nginx_ssl }}/dhparams.pem"

nginx_catalog_list:
  - { path: "{{ nginx_static_root }}", owner: "www-data", group: "www-data", mode: "0755" }
  - { path: "{{ nginx_conf_root }}", owner: "www-data", group: "www-data", mode: "0755" }
  - { path: "{{ nginx_var_root }}", owner: "www-data", group: "www-data", mode: "0755" }
  - { path: "{{ nginx_log_root }}", owner: "www-data", group: "www-data", mode: "0755" }
  - { path: "{{ nginx_common }}", owner: "www-data", group: "www-data", mode: "0755" }
  - { path: "{{ nginx_conf_d }}", owner: "www-data", group: "www-data", mode: "0755" }
  - { path: "{{ nginx_ssl }}", owner: "www-data", group: "www-data", mode: "0755" }

nginx_pid_path: "{{ nginx_var_root }}/nginx.pid"
nginx_err_log_path: "{{ nginx_log_root }}/error.log"
nginx_access_log_path: "{{ nginx_log_root }}/access.log"
nginx_mime_types_path: "{{ nginx_conf_root }}/mime.types"
nginx_include_conf_path_list: []
