nginx_check_prerequisites: true
nginx_generate_dhparams: true
nginx_generate_configs: true
nginx_template_service: true

nginx_base_dir: "{{ services_apps_root }}/nginx"
nginx_log_base_dir: "{{ services_logs_root }}/nginx"

nginx_instance_dir: "{{ nginx_base_dir }}/{{ nginx_instance }}"
nginx_static_dir: "{{ nginx_instance_dir }}/static"

nginx_conf_dir: "{{ nginx_instance_dir }}/conf"
nginx_common_dir: "{{ nginx_conf_dir }}/common"
nginx_conf_d_dir: "{{ nginx_conf_dir }}/conf.d"
nginx_ssl_dir: "{{ nginx_conf_dir }}/ssl"

nginx_ssl_live_dir: "{{ nginx_ssl_dir }}/live"
nginx_ssl_custom_dir: "{{ nginx_ssl_dir }}/custom"

nginx_var_dir: "{{ nginx_instance_dir }}/var"
nginx_log_dir: "{{ nginx_log_base_dir }}/{{ nginx_instance }}"


nginx_instance_directories:
  - { path: "{{ nginx_base_dir }}", owner: "www-data", group: "www-data", mode: "0755" }
  - { path: "{{ nginx_log_base_dir }}", owner: "www-data", group: "www-data", mode: "0755" }
  - { path: "{{ nginx_instance_dir }}", owner: "www-data", group: "www-data", mode: "0755" }
  - { path: "{{ nginx_static_dir }}", owner: "www-data", group: "www-data", mode: "0755" }
  - { path: "{{ nginx_conf_dir }}", owner: "www-data", group: "www-data", mode: "0755" }
  - { path: "{{ nginx_common_dir }}", owner: "www-data", group: "www-data", mode: "0755" }
  - { path: "{{ nginx_conf_d_dir }}", owner: "www-data", group: "www-data", mode: "0755" }
  - { path: "{{ nginx_ssl_dir }}", owner: "www-data", group: "www-data", mode: "0755" }
  - { path: "{{ nginx_var_dir }}", owner: "www-data", group: "www-data", mode: "0755" }
  - { path: "{{ nginx_log_dir }}", owner: "www-data", group: "www-data", mode: "0755" }
  - { path: "{{ nginx_ssl_live_dir }}", owner: "www-data", group: "www-data", mode: "0755" }
  - { path: "{{ nginx_ssl_custom_dir }}", owner: "www-data", group: "www-data", mode: "0755" }
nginx_instance_symlinks:
  - { link: "{{ nginx_instance_dir }}/logs", target: "{{ nginx_log_dir }}" }

# instance for ACME-challenge
nginx_acme_instance: "acme"

# ACME-challenges data for all instances
nginx_acme_root: "{{ services_apps_root }}/nginx/{{ nginx_acme_instance }}/static"
