ssh_use_pam: "yes"
ssh_subsystem: "sftp /usr/lib/openssh/sftp-server"
ssh_x11forwarding: "yes"
ssh_print_motd: "no"
ssh_accept_env: "LANG LC_* COLORTERM NO_COLOR"

ssh_permit_root_login: "no"
ssh_password_authentication: "no"
ssh_permit_empty_passwords: "no"
ssh_pubkey_authentication: "yes"
ssh_port: "22"

ssh_include_list:
  - "/etc/ssh/sshd_config.d/*.conf"

ssh_render_configs: true
ssh_restart_service: false
ssh_add_auth_keys: true
