- name: Set allow rules
  community.general.ufw:
    rule: "{{ item.rule | default('allow') }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    from_port: "{{ item.from_port | default(omit) }}"
    to_port: "{{ item.to_port | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
  loop: "{{ firewall_allow_rules_list }}"
