- name: Firewall check prerequisites
  ansible.builtin.import_tasks: 01_check_prerequisites.yml
  when: firewall_check_prerequisites | bool

- name: Firewall set rules
  ansible.builtin.import_tasks: 02_set_rules.yml
  when: firewall_set_rules | bool

- name: Firewall set default policies
  ansible.builtin.import_tasks: 03_default_policy.yml
  when: firewall_default_policy | bool

- name: Firewall enable
  ansible.builtin.import_tasks: 04_enable.yml
  when: firewall_enable | bool
