- name: Set hostname
  ansible.builtin.import_tasks: 01_set_hostname.yml
  when: common_set_hostname | bool

- name: Create groups
  ansible.builtin.import_tasks: 02_create_groups.yml
  when: common_create_groups | bool

- name: Create users
  ansible.builtin.import_tasks: 03_create_users.yml
  when: common_create_users | bool

- name: Create catalogs
  ansible.builtin.import_tasks: 04_create_catalogs.yml
  when: common_create_catalogs | bool
