- name: Run common role
  hosts:
    - production
  become: true
  roles:
    - common
  when: playbook_role_common | bool

- name: Run packages role
  hosts:
    - production
  become: true
  roles:
    - packages
  when: playbook_role_packages | bool

- name: Run ssh role
  hosts:
    - production
  become: true
  roles:
    - ssh
  when: playbook_role_ssh | bool

- name: Run firewall role
  hosts:
    - production
  become: true
  roles:
    - firewall
  when: playbook_role_firewall | bool

- name: Run nginx role
  hosts:
    - production
  become: true
  roles:
    - nginx
  when: playbook_role_nginx | bool
