apt_package_list:
  - curl
  - fail2ban
  - nginx
  - certbot

nginx_static_catalogs:
  - path: /services/apps/nginx/static
    owner: www-data
    group: www-data
    mode: "0755"
  - path: /services/apps/nginx/conf
    owner: www-data
    group: www-data
    mode: "0755"
