packages_apt_install_list:
  - curl
  - git
  - fail2ban
  - nginx
  - certbot
  - python3-certbot-nginx
  - ufw
  - openssl

ssh_port: "24762"

playbook_role_common: true
playbook_role_packages: true
playbook_role_ssh: true
playbook_role_firewall: true
playbook_role_nginx: false
